config/routes.rb
Carvizy::Application.routes.draw do
  resources :messages

  #com parte facebook, sem o mega login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  #nesting de users em cars
  resources :users do
  	resources :cars
  end
  
  match "/all_cars", :to => "cars#all_cars"
  match "/inbox", :to => "messages#inbox"
  match "/submit_car", :to => "home#submit_car"



  resources :profiles


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def submit_car

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="product-showcase">
    <div class="product-showcase-pattern">
        <div class="container" style="height:700px;">
            
            <div class="row">
                <div class="span4 product-background">
                   <%= image_tag "carro2.png" %>
               </div>
              <div class="span1 offset6 product-background" style="text-align:center; color:white;">
<% if current_user.nil? %>
    

                
                   <a href="<%= users_path %>" style="color:white">LOGIN</a>
                   <%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook) %>
               
               <% else %>
<a href="<%= users_path %>" style="color:white">Meu Perfil</a>
           <% end %>
           </div>
           </div>
           
           <div class="row">
            <div class="span1 product-image">
                <div class="span12 product-title">
                    <h1>Partilhe o seu <strong>Carro</strong> e poupe com isso!<h1>
                        <div class="product-description">
                            <form action="assets/subscribe.php" method="post" class="subscribe">
                                <input type="text" name="email" class="email span5" placeholder="Introduza o seu carro do sonho...">
                                <button type="submit">Pesquisa</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="span1 product-image">
                    <div class="span11">
                        <h3><a href="<%= submit_car_path %>" style="color:white; padding:5px; border: 3px solid white; border-radius: 5px;"> Liste o Seu Carro > </a></h3>
                    </div>
                </div>
            </div> 
        </div>
    </div>

</div>
<!-- Content -->
<div class="container">

    <div class="row">
        <div class="span12">
            <!-- features -->
            <div class="features_2">
                <h3>Os nossos melhores carros</h3>
                <div class="row">
                    <div class="span4 single-feature features-left-span showa show-third">
                        <img src="<%= asset_path 'cars/lambo.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>

                    <div class="span4 single-feature showa show-third">
                        <img src="<%= asset_path 'cars/caravan.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>
                    
                    <div class="span4 single-feature  showa show-third">
                        <img src="<%= asset_path 'cars/lotus.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="span4 single-feature features-left-span showa show-third">
                        <img src="<%= asset_path 'cars/mini.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>

                    <div class="span4 single-feature showa show-third">
                        <img src="<%= asset_path 'cars/limo.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>
                    
                    <div class="span4 single-feature  showa show-third">
                        <img src="<%= asset_path 'cars/tesla.jpg' %>" class="img-polaroid"/>
                        <div class="mask">
                            <h2>Zoidberg</h2>
                            <p>$14.00</p>
                            <a href="#" class="more">More info</a>
                        </div>
                    </div>
                    
                </div>
                <div class="span12 text-center">
                    <h4><a href="#" style="color:#333;" > Ver Mais > </a></h4>
                </div>
            </div>
        </div>
    </div> <!-- end row -->

    <div class="row">
        <div class="span12">
            <!-- about us -->
            <div class="about-us_2">
                <h3>Sobre Nós</h3>
                <h5>CARVIZ é um clube de partilha de automóveis, motos, barcos e bicicletas que funciona com base na confiança e proximidade entre proprietário e utilizador</h5>
                <p>Gostava de usar o jeep, a autocaravana ou o Smart do seu vizinho? De levar um Mercedes ao casamento da sua sobrinha? Como não tem nenhum destes veículos, a solução é pedi-los emprestados, mas é provável que receie uma resposta negativa.
                    <br/>
                    Gostava de fazer algum dinheiro com o veículo que acaba de comprar e afinal quase não usa? Vai viajar para o estrangeiro e o carro fica parado à sua porta? Como disponibilizá-lo a alguém da sua confiança que, ainda por cima, mora na porta ao lado?
                </p>
                <% @users.each do |user| %>
                <p>User: <%=link_to user.name, user %></p>
                <% end %>
                
                <%= render 'layouts/messages' %>
            </div>
        </div>
    </div> <!-- end row -->

    
            <!-- as seen on 
            <div class="row">
            <div class="span12 using-this">
                <h3>Como Visto Em...</h3>
                <div class="using-this-container">
                    <a class="using-this-google" href="#"></a>
                    <a class="using-this-pinterest" href="#"></a>
                    <a class="using-this-youtube" href="#"></a>
                    <a class="using-this-google" href="#"></a>
                    <a class="using-this-pinterest" href="#"></a>
                </div>
            </div>
        </div> 
        <!-- end row -->
    </div> <!-- end container -->

app/views/home/submit_car.html.erb
<div class="product-showcase">
    <div class="product-showcase-pattern">
        <div class="container" style="height:200px;">
            
            <div class="row">
                <div class="span4 product-background">
                   <%= image_tag "carro2.png" %>
               </div>
              <div class="span1 offset6 product-background" style="text-align:center; color:white;">
<% if current_user.nil? %>
    

                
                   <a href="<%= users_path %>" style="color:white">LOGIN</a>
                   <%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook) %>
               
               <% else %>
<a href="<%= users_path %>" style="color:white">Meu Perfil</a>
           <% end %>
           </div>
           </div>
           
          
                </div>

            </div>
           
        </div>
    </div>

</div>
<!-- Content -->
<div class="container">

        

    <div class="row">
        <div class="span12">
            <!-- about us -->
            <div class="about-us_2">
                <h3>Submeter o Seu Carro</h3>
               <!-- Change the width and height values to suit you best -->
<div class="typeform-widget" data-url="https://carviz.typeform.com/to/CPRNiO" data-text="Carviz" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
              
            </div>
        </div>
    </div> <!-- end row -->

    
            <!-- as seen on 
            <div class="row">
            <div class="span12 using-this">
                <h3>Como Visto Em...</h3>
                <div class="using-this-container">
                    <a class="using-this-google" href="#"></a>
                    <a class="using-this-pinterest" href="#"></a>
                    <a class="using-this-youtube" href="#"></a>
                    <a class="using-this-google" href="#"></a>
                    <a class="using-this-pinterest" href="#"></a>
                </div>
            </div>
        </div> 
        <!-- end row -->
    </div> <!-- end container -->