config/routes.rb
Carvizy::Application.routes.draw do
  resources :messages

  #com parte facebook, sem o mega login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  #nesting de users em cars
  resources :users do
  	resources :cars
  end
  
  match "/all_cars", :to => "cars#all_cars"
  match "/inbox", :to => "messages#inbox"
  match "/submit_car", :to => "home#submit_car"



  resources :profiles


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :ano, :cor, :kilometragem, :marca, :modelo, :variacao,:carphoto
  mount_uploader :carphoto, CarPhotoUploader
  belongs_to :user
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    #este index sera o geral para todos os carros, ou temos que ter um user cars...
    @cars = User.find(params[:user_id]).cars

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  def all_cars
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new
    @user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end

  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.build(params[:car])
    respond_to do |format|
      if @car.save
        format.html { redirect_to [@car.user, @car], notice: 'Car was successfully created.' }
        format.json { render json: [@car.user, @car], status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to user_cars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
             <%= form_for [@user, @car], :html =>{:multipart => true} do |f| %>
             <% if @car.errors.any? %>
             <div id="error_explanation">
              <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
              <ul>
                <% @car.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>

            <div class="span3 offset2">
              <div class="logowrapper">
                <img class="logoicon" src="http://placehold.it/300x300/bbb/&text=Car+Image" alt="App Logo"/>
                <%= f.file_field :carphoto %>
              </div>
            </div>
            <div class="span6">
              <form class="form-horizontal">
                <p class="help-block">Marca</p>
                <div class="input-prepend">
                  <%= f.text_field :marca, :size => "16" %>
                </div>
                <p class="help-block">Modelo</p>
                <div class="input-prepend">
                  <%= f.text_field :modelo, :size => "16" %>
                </div>
                <div class="field">
                  <%= f.label :variacao %>
                  <%= f.text_field :variacao %>

                  <%= f.label :cor %>
                  <%= f.text_field :cor %>

                  <%= f.label :ano %>
                  <%= f.number_field :ano %>

                  <%= f.label :kilometragem %>
                  <%= f.text_field :kilometragem %>
                </div>
                <hr>
                <div class="help-block">
                  <%= f.submit %>
                </div>
              </form>
            </div>
          </div>

          <% end %>

app/views/cars/all_cars.html.erb
<h1>Listing all cars</h1>


<table>
  <tr>
    <th>proprietario</th>
    <th>Marca</th>
    <th>Ano</th>
    <th>Modelo</th>
    <th>Variacao</th>
    <th>Cor</th>
    <th>Kilometragem</th>
    <th></th>
</tr>
<% @cars.each do |car| %>
<tr>
    <td><%= car.user.name %></td>
    <td><%= car.marca %></td>
    <td><%= car.ano %></td>
    <td><%= car.modelo %></td>
    <td><%= car.variacao %></td>
    <td><%= car.cor %></td>
    <td><%= car.kilometragem %></td>
    <td><%= link_to 'Show', user_car_path(car, car.user) %></td>
</tr>
<% end %>
</table>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>proprietario</th>
    <th>Marca</th>
    <th>Ano</th>
    <th>Modelo</th>
    <th>Variacao</th>
    <th>Cor</th>
    <th>Kilometragem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.user.name %></td>
    <td><%= car.marca %></td>
    <td><%= car.ano %></td>
    <td><%= car.modelo %></td>
    <td><%= car.variacao %></td>
    <td><%= car.cor %></td>
    <td><%= car.kilometragem %></td>
    <td><%= link_to 'Show', user_car_path(car.user, car) %> -
    <%= link_to 'Edit', edit_user_car_path(car.user, car)%>
     - <%= link_to 'Destroy', user_car_path(car.user, car), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_user_car_path %>

app/views/cars/new.html.erb
<div class="row">
	<div class="span12">
		<h3>Dados da Viatura</h3>
		<%= render 'form' %>
	</div>
</div>
<%= link_to 'Back', user_cars_path %>

app/views/cars/show.html.erb
    <%= render 'layouts/menu' %>

    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="<%= @car.carphoto %>" alt="">
        </div>
        <div class="item">
          <img src="<%= @car.carphoto %>" alt="">
        </div>

      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container">

      <!-- Three columns of text below the carousel -->
      <div class="row">
<p id="notice"><%= notice %></p>

        <div class="span7">
         <h2> <%= @car.marca %> -  <%= @car.modelo %></h2> <h4>   <%= @car.variacao %>
  <%= @car.ano %>
  <%= @car.cor %>
  <%= @car.kilometragem %></h4>


         <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
         <h4>Regras</h4>
         <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
         <%= link_to 'Edit', edit_user_car_path(@car.user, @car) %> |
<%= link_to 'Back', user_cars_path %>
         <hr>
         <div class="span2 card-mini text-center">
          <h4>Preço por Dia</h4>
          <h1>100€</h1>
          <a href="#" class="btn btn-warning">Alugar</a>
        </div>
        
        <div class="span2 card-mini text-center">
          <h4>Preço por Semana</h4>
          <h1>400€</h1>
          <a href="#" class="btn btn-warning">Alugar</a>

        </div>

        <div class="span2 card-mini text-center">
          <h4>Preço por Mês</h4>
          <h1>4000€</h1>
          <a href="#" class="btn btn-warning">Alugar</a>

        </div>

      </div><!-- /.span4 -->
      <div class="span3 pull-right card text-center">
        <img src="<%= @car.user.profile.avatar %>" class="img-polaroid img-circle" />
        <h4><%= @car.user.name %></h4>
        <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-warning btn-large" href="#">Contactar o Dono &raquo;</a></p>
      </div><!-- /.span4 -->
    </div><!-- /.row -->

  </div>